#!/usr/bin/env bash

# =====================================
# Set cwd to vip-quickstart
# =====================================
DIR="$( dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) )"
ORIG=`pwd`
cd $DIR/..

vagrant up $1
cp -f /etc/hosts pmc/hosts.backup
cp -f /etc/hosts pmc/hosts
vagrant ssh -c /srv/pmc/setup-sites.sh -- -t
cp -f pmc/hosts /etc/hosts

# =====================================
# Reset cwd
# =====================================
cd $ORIG
